name: Deployment Excercise 2

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code 
        uses: actions/checkout@v4.2.2
     
      - name: Install dependencies
        run: npm install
        working-directory: '04 Practice Project (Start)'
        
      - name: Lint
        run: npm run lint
        working-directory: '04 Practice Project (Start)'
        
      - name: Build code 
        run : npm run build
        working-directory: '04 Practice Project (Start)'
        
      - name: Test code
        run: npm run test
        working-directory: '04 Practice Project (Start)'

      - name: Check if secret exists
        run: |
          if [ -z "${SECRET}" ]; then
            echo "❌ Secret is EMPTY"
          else
            echo "✅ Secret is SET"
          fi
          env:
            SECRET: ${{ secrets.MY_PASSWORD }}
  
