name: Hnadle issues

on: 
  pull_request: 
    types: 
      - opened 

jobs: 
  output-info: 
    runs-on: ubuntu-latest
    steps: 
      - name: Ouput event details
        run: echo "${{ toJSON(github.event) }}"
  
